### ISSUE TITLE
The results for TransE

### ISSUE THREAD

**Issue by liu-jc** [idirlab/kgcompletion#2]

**Comment by liu-jc** [comment]
Dear authors,

I have run your experiments for TransE. I got two kinds of results. One for type constraint results and the other one for no type constraint results. I would like to know the results reported in the paper should be type constrained, right? 
And I wonder whether you could provide more details about how to get the equivalent/similar results with those reported in the paper using this repo. Thanks a lot.

**Comment by fa-cse** [comment]
Hi, Results are the no type constraint. For TransE results on FB15k and FB15k-237, we used the hyperparameters provided by OpenKE.
